# @format

# # @format

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     io.kompose.service: pg-bill-microservice
#   name: pg-bill-microservice
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: pg-bill-microservice
#   template:
#     metadata:
#       labels:
#         io.kompose.service: pg-bill-microservice
#     spec:
#       containers:
#         - args:
#             - npm
#             - startdock
#           env:
#             - name: DB_DATABASE
#               value: pg-bill
#             - name: DB_HOST
#               value:
#             - name: DB_PASSWORD
#               value: root
#             - name: DB_PORT
#               value: "3306"
#             - name: DB_USERNAME
#               value: root
#           image: antoniopapa/ambassador:0.0.1
#           name: ambassador-backend
#           ports:
#             - containerPort: 8080
#           resources:
#             requests:
#               cpu: "100m"
#               memory: "128Mi"
#             limits:
#               cpu: "100m"
#               memory: "128Mi"
# ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      # volumes:
      #   - name: mysql-storage
      #     persistentVolumeClaim:
      #       claimName: database-persistent-volume-claim
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          # volumeMounts:
          #   - name: mysql-storage
          #     mountPath: /var/lib/mysql
          #     subPath: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
