# @format

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pg-bill-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: pg-bill.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: pg-bill-service
                port:
                  number: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /.data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: pg-bill-service
spec:
  type: ClusterIP
  selector:
    app: pg-bill-server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-bill-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-bill-server
  template:
    metadata:
      labels:
        app: pg-bill-server
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: pg-bill
            - name: DB_HOST
              value: mysql-cluster-ip-service.default
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
          image: 2020mt93721/paying-guest-bill-sevice:v0.0.1
          name: pg-server
          ports:
            - containerPort: 8080
#           resources:
#             requests:
#               cpu: "100m"
#               memory: "128Mi"
#             limits:
#               cpu: "100m"
#               memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: pg-bill
            - name: MYSQL_ROOT_PASSWORD
              value: root
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
